# Generated by Django 3.1 on 2020-08-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moveset',
            name='weave_damage',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='compound_resistance',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='compound_weakness',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='feeble',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='immune',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='puny',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='resistant',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='strong',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='weak',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
