# Generated by Django 3.0.7 on 2020-06-30 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0001_squashed_0034_cpm_buddy_cpm'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='shadow',
            field=models.BooleanField(default=False),
        ),
    ]
