# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-29 21:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0001_squashed_0022_merge_20180926_2005'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={},
        ),
        migrations.AlterModelOptions(
            name='moveset',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AlterModelOptions(
            name='weathercondition',
            options={'verbose_name': 'Weather Condition', 'verbose_name_plural': 'Weather Conditions'},
        ),
    ]
