# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-04 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
