# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0002_move_legacy'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='cp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='CP'),
        ),
    ]
