# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-30 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0002_auto_20170629_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpm',
            name='raid_cpm',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cpm',
            name='raid_tier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='raid_cpm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgo.CPM', verbose_name='Raid CPM'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='raid_stamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Raid Stamina'),
        ),
    ]
