# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-02 19:02
from __future__ import unicode_literals

from django.db import migrations


def migrate_pokemon_moves(apps, schema_editor):
    Pokemon = apps.get_model('pgo', 'Pokemon')
    PokemonMove = apps.get_model('pgo', 'PokemonMove')

    for pokemon in Pokemon.objects.all():
        quick_moves = PokemonMove.objects.filter(
            pokemon=pokemon, move_id__in=pokemon.quick_moves.values_list('id'))
        cinematic_moves = PokemonMove.objects.filter(
            pokemon=pokemon, move_id__in=pokemon.cinematic_moves.values_list('id'))
        pokemon.quick_moves.set(quick_moves)
        pokemon.cinematic_moves.set(cinematic_moves)
        pokemon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0003_auto_20180929_2250'),
    ]

    operations = [
        migrations.RunPython(migrate_pokemon_moves, migrations.RunPython.noop)
    ]
