# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-05 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0003_pokemon_cp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='cp',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='maximum_cp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Maximum Combat Power'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pgo_attack',
            field=models.IntegerField(blank=True, null=True, verbose_name='PGO Attack'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pgo_defense',
            field=models.IntegerField(blank=True, null=True, verbose_name='PGO Defense'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pgo_stamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='PGO Stamina'),
        ),
    ]
