# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-15 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0003_auto_20170730_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidTier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.PositiveIntegerField(verbose_name='Tier Level')),
                ('tier_stamina', models.PositiveIntegerField(verbose_name='Tier Stamina')),
                ('raid_cpm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.CPM', verbose_name='Raid CPM')),
            ],
            options={
                'ordering': ('-tier',),
                'verbose_name': 'Raid Tier',
                'verbose_name_plural': 'Raid Tiers',
            },
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='raid_cpm',
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='raid_stamina',
            field=models.IntegerField(blank=True, null=True, verbose_name='Override for raid stamina'),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='raid_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pgo.RaidTier', verbose_name='Raid Tier'),
        ),
    ]
