# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0004_auto_20170815_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaidBoss',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.Pokemon', verbose_name='Pokemon')),
                ('raid_tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.RaidTier', verbose_name='Raid Tier')),
            ],
        ),
        migrations.AlterModelOptions(
            name='cpm',
            options={'ordering': ('-raid_cpm', 'level'), 'verbose_name': 'CP multiplier', 'verbose_name_plural': 'CP multiplier'},
        ),
    ]
