# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-03 21:04
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0004_auto_20181002_1902'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('number',), 'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AddField(
            model_name='pokemon',
            name='generation',
            field=models.CharField(blank=True, choices=[('I', 'I'), ('II', 'II'), ('III', 'III'), ('IV', 'IV'), ('V', 'V'), ('VI', 'VI'), ('VII', 'VII'), ('VIII', 'VIII')], max_length=5),
        ),
    ]
