# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-08-19 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0005_auto_20170819_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='raidboss',
            options={'ordering': ('-raid_tier__tier', 'pokemon__name'), 'verbose_name': 'Raid Boss', 'verbose_name_plural': 'Raid Bosses'},
        ),
    ]
