# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-10-03 20:31
from django.db import migrations

from pgo.models import Generation


def assign_generations(apps, schema_editor):
    Pokemon = apps.get_model('pgo', 'Pokemon')

    def assign_generation(pokemon_qs, generation):
        for pokemon in pokemon_qs:
            pokemon.generation = generation
            pokemon.save()

    pokemon_qs = Pokemon.objects.exclude(name__icontains='(A)')

    genI = pokemon_qs.all()[:151]
    assign_generation(genI, Generation.I)

    genII = pokemon_qs.all()[151:251]
    assign_generation(genII, Generation.II)

    genIII = pokemon_qs.all()[251:386]
    assign_generation(genIII, Generation.III)

    genIV = pokemon_qs.all()[386:]
    assign_generation(genIV, Generation.IV)

    alola_qs = Pokemon.objects.filter(name__icontains='(A)')
    for pokemon in alola_qs:
        pokemon.generation = Generation.VII
        pokemon.number = pokemon.number.replace('a', '')
        pokemon.slug = pokemon.slug.replace('-a', '-alolan')
        pokemon.name = pokemon.name.replace('(A)', '(Alolan)')
        pokemon.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0005_auto_20181003_2104'),
    ]

    operations = [
        migrations.RunPython(assign_generations, migrations.RunPython.noop)
    ]
