# Generated by Django 2.1.3 on 2018-11-20 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0006_auto_20181003_2107'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topcounter',
            unique_together={('defender', 'weather_condition', 'counter')},
        ),
    ]
