# Generated by Django 2.1.3 on 2018-11-20 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0007_auto_20181120_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topcounter',
            name='defender_cpm',
        ),
    ]
