# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-06 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0008_cpm_powerup_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpm',
            name='total_powerup_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
