# Generated by Django 2.1.3 on 2018-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0008_remove_topcounter_defender_cpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeeffectivnessscalar',
            name='scalar',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
