# Generated by Django 2.1.3 on 2019-01-06 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0009_auto_20181213_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='move',
            name='dpe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=5, null=True, verbose_name='Damage per energy'),
        ),
        migrations.AddField(
            model_name='move',
            name='dpt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Damage per turn'),
        ),
        migrations.AddField(
            model_name='move',
            name='ept',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Energy per turn'),
        ),
        migrations.AddField(
            model_name='move',
            name='pvp_duration',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='pvp_energy_delta',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='move',
            name='pvp_power',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='move',
            name='dps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Damage per second'),
        ),
        migrations.AlterField(
            model_name='move',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='Energy per second'),
        ),
    ]
