# Generated by Django 2.1.3 on 2019-01-10 08:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0010_auto_20190106_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='compound_resistance',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='compound_weakness',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
