# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-09 16:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgo', '0011_weathercondition'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonMove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('legacy', models.BooleanField(default=False)),
                ('stab', models.BooleanField(default=False)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('move', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.Move')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.Pokemon')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('pokemon', '-stab', '-score'),
            },
        ),
        migrations.AddField(
            model_name='moveset',
            name='cinematic_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cinematic_moves', to='pgo.PokemonMove'),
        ),
        migrations.AddField(
            model_name='moveset',
            name='quick_move',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quick_moves', to='pgo.PokemonMove'),
        ),
        migrations.AlterUniqueTogether(
            name='pokemonmove',
            unique_together=set([('pokemon', 'move')]),
        ),
    ]
