# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0012_auto_20180209_1627'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weathercondition',
            options={'verbose_name': 'Weather Condition', 'verbose_name_plural': 'Weather Conditions'},
        ),
        migrations.AddField(
            model_name='weathercondition',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weathercondition',
            name='types_boosted',
            field=models.ManyToManyField(blank=True, to='pgo.Type', verbose_name='Boosts Type'),
        ),
    ]
