# Generated by Django 2.1.3 on 2019-01-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0012_auto_20190110_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='bulk',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='stat_product',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
