# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-22 21:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0013_auto_20180311_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidboss',
            name='status',
            field=models.CharField(blank=True, choices=[('anticipated', 'Anticipated'), ('current', 'Current'), ('exclusive', 'Exclusive'), ('past', 'Past')], max_length=20),
        ),
    ]
