# Generated by Django 2.1.3 on 2019-01-27 10:44

from django.db import migrations


def calculate_stat_product_and_bulk(apps, schema_editor):
    Pokemon = apps.get_model('pgo', 'Pokemon')

    for p in Pokemon.objects.all():
        p.stat_product = p.pgo_attack + p.pgo_defense + p.pgo_stamina
        p.bulk = p.pgo_defense * p.pgo_stamina
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0013_auto_20190127_1048'),
    ]

    operations = [
        migrations.RunPython(
            calculate_stat_product_and_bulk,
            migrations.RunPython.noop
        ),
    ]
