# Generated by Django 2.1.5 on 2019-02-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0014_auto_20190127_1048'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='topcounter',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='topcounter',
            name='counter',
        ),
        migrations.RemoveField(
            model_name='topcounter',
            name='defender',
        ),
        migrations.RemoveField(
            model_name='topcounter',
            name='weather_condition',
        ),
        migrations.DeleteModel(
            name='TopCounter',
        ),
    ]
