# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-30 21:43
from __future__ import unicode_literals

from django.db import migrations, models


def add_candy_costs(apps, schema_editor):
    CPM = apps.get_model('pgo', 'CPM')
    candy_cost_per_powerup = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
        4, 4, 4, 4, 4, 4, 4, 4, 4, 4,
        6, 6, 6, 6,
        8, 8, 8, 8,
        10, 10, 10, 10,
        12, 12, 12, 12,
        15, 15
    ]

    total_candy_cost = 0
    for i, cpm in enumerate(CPM.objects.filter(raid_cpm=False).exclude(level=40.0)):
        cpm.candy_cost = candy_cost_per_powerup[i]
        cpm.total_candy_cost = total_candy_cost
        cpm.save()
        total_candy_cost += candy_cost_per_powerup[i]


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0014_raidboss_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cpm',
            old_name='powerup_cost',
            new_name='stardust_cost',
        ),
        migrations.RenameField(
            model_name='cpm',
            old_name='total_powerup_cost',
            new_name='total_stardust_cost',
        ),
        migrations.AddField(
            model_name='cpm',
            name='candy_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cpm',
            name='total_candy_cost',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(add_candy_costs, migrations.RunPython.noop)
    ]
