# Generated by Django 2.1.5 on 2019-02-04 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0015_auto_20190201_2303'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeEffectivness',
            new_name='TypeEffectiveness',
        ),
        migrations.RenameModel(
            old_name='TypeEffectivnessScalar',
            new_name='TypeEffectivenessScalar',
        ),
        migrations.RenameField(
            model_name='typeeffectiveness',
            old_name='effectivness',
            new_name='effectiveness',
        ),
    ]
