# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-13 11:35
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0015_auto_20180330_2143'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defender_cpm', models.DecimalField(decimal_places=9, max_digits=10)),
                ('highest_dps', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='Highest DPS')),
                ('moveset_data', django.contrib.postgres.fields.jsonb.JSONField()),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='counters', to='pgo.Pokemon')),
                ('defender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defenders', to='pgo.Pokemon')),
                ('weather_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.WeatherCondition')),
            ],
        ),
        migrations.AlterModelOptions(
            name='pokemonmove',
            options={'ordering': ('pokemon', '-score', '-stab')},
        ),
        migrations.AlterUniqueTogether(
            name='topcounter',
            unique_together=set([('defender', 'defender_cpm', 'weather_condition', 'counter')]),
        ),
    ]
