# Generated by Django 2.1.5 on 2019-02-05 22:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0016_auto_20190204_0814'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_from', models.DateField(default=datetime.datetime(2016, 7, 6, 0, 0))),
                ('available_to', models.DateField(blank=True, null=True)),
                ('legacy_status', models.CharField(blank=True, choices=[('CD', 'Community day'), ('RD', 'Raid day'), ('QE', 'Quest encounter'), ('RM', 'Removed'), ('AC', 'Active')], default='AC', max_length=2, null=True)),
            ],
            options={
                'verbose_name': 'Move availability',
                'verbose_name_plural': 'Move availability',
            },
        ),
        migrations.RemoveField(
            model_name='pokemonmove',
            name='legacy',
        ),
        migrations.RemoveField(
            model_name='moveset',
            name='legacy',
        ),
        migrations.AlterUniqueTogether(
            name='moveset',
            unique_together={('pokemon', 'quick_move', 'cinematic_move')},
        ),
        migrations.AddField(
            model_name='moveavailability',
            name='pokemon_move',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pgo.PokemonMove'),
        ),
    ]
