# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-20 19:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0016_auto_20180513_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidtier',
            name='battle_duration',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
