# Generated by Django 2.1.5 on 2019-02-05 22:49

from django.db import migrations


def create_move_availability(apps, schema_editor):
    MoveAvailability = apps.get_model('pgo', 'MoveAvailability')
    PokemonMove = apps.get_model('pgo', 'PokemonMove')

    MoveAvailability.objects.bulk_create([
        MoveAvailability(pokemon_move_id=pm_id)
        for pm_id in PokemonMove.objects.values_list('id', flat=True)
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0017_auto_20190205_2236'),
    ]

    operations = [
        migrations.RunPython(
            create_move_availability,
            migrations.RunPython.noop
        ),
    ]
