# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-09 12:34
from __future__ import unicode_literals
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0017_raidtier_battle_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='topcounter',
            name='counter_hp',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='topcounter',
            name='multiplier',
            field=models.DecimalField(blank=True, decimal_places=27, max_digits=29, null=True),
        ),
        migrations.AddField(
            model_name='topcounter',
            name='score',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
