# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-25 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0018_auto_20180609_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='implemented',
            field=models.BooleanField(default=True),
        ),
    ]
