# Generated by Django 2.1.5 on 2019-02-06 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0019_auto_20190205_2257'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='cinematic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemonmove',
            name='move_type',
            field=models.CharField(choices=[('bug', 'Bug'), ('dark', 'Dark'), ('dragon', 'Dragon'), ('electric', 'Electric'), ('fairy', 'Fairy'), ('fighting', 'Fighting'), ('fire', 'Fire'), ('flying', 'Flying'), ('ghost', 'Ghost'), ('grass', 'Grass'), ('ground', 'Ground'), ('ice', 'Ice'), ('normal', 'Normal'), ('poison', 'Poison'), ('psychic', 'Psychic'), ('rock', 'Rock'), ('steel', 'Steel'), ('water', 'Water')], default='normal', max_length=10),
        ),
    ]
