# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-21 22:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0020_auto_20180626_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='raidtier',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
