# Generated by Django 2.1.5 on 2019-02-06 22:09

from django.db import migrations


def migrate_move_properties(apps, schema_editor):
    PokemonMove = apps.get_model('pgo', 'PokemonMove')

    for pm in PokemonMove.objects.select_related('move__move_type'):
        pm.move_type = pm.move.move_type.slug
        pm.cinematic = pm.move.category == 'CC'
        pm.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0020_auto_20190206_2209'),
    ]

    operations = [
        migrations.RunPython(
            migrate_move_properties,
            migrations.RunPython.noop
        ),
    ]
