# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models

from pgo.models import RaidBossStatus


def update_raid_boss_status(apps, schema_editor):
    RaidBoss = apps.get_model('pgo', 'RaidBoss')

    RaidBoss.objects.exclude(status='').update(status=RaidBossStatus.OFFICIAL)


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0020_auto_20180626_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raidboss',
            name='status',
            field=models.CharField(blank=True, choices=[('official', 'Official'), ('simulated', 'Simulated')], max_length=20),
        ),
        migrations.RunPython(update_raid_boss_status, migrations.RunPython.noop)
    ]
