# Generated by Django 2.1.5 on 2019-02-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0021_auto_20190206_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemonmove',
            name='legacy',
            field=models.BooleanField(default=False),
        ),
    ]
