# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-09-26 20:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0021_auto_20180923_1658'),
        ('pgo', '0021_raidtier_order'),
    ]

    operations = [
    ]
