# Generated by Django 2.1.5 on 2019-02-07 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0022_pokemonmove_legacy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonmove',
            name='score',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
