# Generated by Django 2.1.5 on 2019-02-07 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0024_auto_20190207_0830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='move',
            name='active',
        ),
        migrations.RemoveField(
            model_name='move',
            name='created',
        ),
        migrations.RemoveField(
            model_name='move',
            name='user',
        ),
        migrations.RemoveField(
            model_name='moveset',
            name='active',
        ),
        migrations.RemoveField(
            model_name='moveset',
            name='created',
        ),
        migrations.RemoveField(
            model_name='moveset',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pokemonmove',
            name='active',
        ),
        migrations.RemoveField(
            model_name='pokemonmove',
            name='created',
        ),
        migrations.RemoveField(
            model_name='pokemonmove',
            name='user',
        ),
        migrations.RemoveField(
            model_name='type',
            name='active',
        ),
        migrations.RemoveField(
            model_name='type',
            name='created',
        ),
        migrations.RemoveField(
            model_name='type',
            name='user',
        ),
        migrations.RemoveField(
            model_name='weathercondition',
            name='active',
        ),
        migrations.RemoveField(
            model_name='weathercondition',
            name='created',
        ),
        migrations.RemoveField(
            model_name='weathercondition',
            name='user',
        ),
    ]
