# Generated by Django 2.1.5 on 2019-02-10 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0025_auto_20190207_0841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='stat_product',
            new_name='stat_sum',
        ),
    ]
