# Generated by Django 2.1.5 on 2019-02-18 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0026_auto_20190210_1122'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeEffectivenessScalar',
            new_name='EffectivenessScalar',
        ),
        migrations.RemoveField(
            model_name='typeeffectiveness',
            name='effectiveness',
        ),
        migrations.RemoveField(
            model_name='typeeffectiveness',
            name='type_defense',
        ),
        migrations.RemoveField(
            model_name='typeeffectiveness',
            name='type_offense',
        ),
        migrations.DeleteModel(
            name='TypeEffectiveness',
        ),
    ]
