# Generated by Django 2.1.5 on 2019-02-19 23:31

from django.db import migrations, models


def calculate_stat_product(apps, schema_editor):
    Pokemon = apps.get_model('pgo', 'Pokemon')

    for p in Pokemon.objects.all():
        p.stat_product = p.pgo_attack * p.pgo_defense * p.pgo_stamina
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0027_auto_20190218_0903'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='stat_product',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RunPython(
            calculate_stat_product,
            migrations.RunPython.noop
        ),
    ]
