# Generated by Django 2.2.3 on 2019-07-26 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0028_pokemon_stat_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='level',
            field=models.CharField(max_length=12),
        ),
    ]
