# Generated by Django 2.2.5 on 2019-09-06 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0029_auto_20190726_0910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='move',
            options={'ordering': ('-category', 'name')},
        ),
    ]
