# Generated by Django 2.2.5 on 2019-09-24 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0030_auto_20190906_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='raidboss',
            name='status',
        ),
    ]
