# Generated by Django 2.2.5 on 2019-09-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0032_auto_20190925_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='move',
            name='dpe',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True, verbose_name='Damage per energy'),
        ),
        migrations.AlterField(
            model_name='move',
            name='dps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Damage per second'),
        ),
        migrations.AlterField(
            model_name='move',
            name='dpt',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Damage per turn'),
        ),
        migrations.AlterField(
            model_name='move',
            name='eps',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Energy per second'),
        ),
        migrations.AlterField(
            model_name='move',
            name='ept',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True, verbose_name='Energy per turn'),
        ),
    ]
