# Generated by Django 2.2.6 on 2019-12-27 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pgo', '0033_auto_20190929_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpm',
            name='buddy_cpm',
            field=models.BooleanField(default=False),
        ),
    ]
