# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-10 21:29
from __future__ import unicode_literals

import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainer',
            options={'ordering': ('nickname',)},
        ),
        migrations.AlterField(
            model_name='trainer',
            name='nickname',
            field=django.contrib.postgres.fields.citext.CICharField(default='', max_length=15, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]{4,}$', 'Nicknames are 4-15 characters long and consist only of letters and numbers.')]),
            preserve_default=False,
        ),
    ]
