# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-15 20:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0002_auto_20171010_2129'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('slug',)},
        ),
    ]
