# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_auto_20171021_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.Team'),
        ),
    ]
