# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-10-26 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_auto_20171025_0707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ('-trainer_count',)},
        ),
        migrations.AlterModelOptions(
            name='town',
            options={'ordering': ('-trainer_count',)},
        ),
    ]
