# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 07:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_auto_20171026_0656'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.RemoveField(
            model_name='town',
            name='country',
        ),
        migrations.RemoveField(
            model_name='town',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='team',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='towns',
        ),
        migrations.RemoveField(
            model_name='trainer',
            name='user',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Town',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
