# Generated by Django 2.2.5 on 2019-09-30 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zenofewords', '0002_sitenotification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navigationitem',
            name='navigation',
        ),
        migrations.RemoveField(
            model_name='navigationitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sitenotification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Navigation',
        ),
        migrations.DeleteModel(
            name='NavigationItem',
        ),
        migrations.DeleteModel(
            name='SiteNotification',
        ),
    ]
