# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0002_auto_20170809_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stat',
            name='user',
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
    ]
